name: Passing Values To Next Steps

on: push

jobs:
  passing_values_btw_steps:
    runs-on: ubuntu-latest
    steps: 
      - name: Set the value using ENV Vars
        run: |
          echo "variable_name=this-is-value" >> $GITHUB_ENV

      - name: Create Variables
        id: var_source_step
        run: |
          echo "Performing a random task"
          echo "var1_name=TechSchool" >> $GITHUB_OUTPUT
          echo "var2_date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Get variable value
        run: |
          echo "Printing the values"
          echo "variable_name: ${{ env.variable_name }}"
          echo "var1_name: ${{ steps.var_source_step.outputs.var1_name }}"
          echo "var2_date: ${{ steps.var_source_step.outputs.var2_date }}"
