name: Artifacts Tutorial

on: push

jobs:
  upload_artifact_job:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create a local file
        run: echo "Hi, I am storing this data in this file, so I can use this in the subsequent jobs within this workflow run. I will upload this file to GitHub storage and download it from there when needed in this workflow run." > file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt

  download_artifact_job:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: upload_artifact_job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: file

      - name: Show file contents
        run: cat file.txt
