name: My First GitHub Action

on:
  push:
    branches:
      - main

env:
  my_first_var: first variable yay!
  my_second_var: second variable yes!
  my_third_var: third variable wowza!

jobs:
  build-app:
    name: My first job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello, world!"

      - name: Run multiple commands
        run: |
          echo "My first command"
          echo "My second command"

      - name: Test env variables
        run: |
          echo "${{ env.my_first_var }}"
          echo "${{ env.my_second_var }}"
          echo "${{ env.my_third_var }}"

      - name: Fetch default environment variables
        run: env

  test-default-vars:
    name: Default env vars job
    runs-on: ubuntu-latest

    steps:
      - name: Example default env vars
        run: |
          echo "${{ env.GITHUB_ACTION }}"
